version: '3.1'
services:
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=insurance-db
  redis-server:
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"